name: purwita_flutter_project
description: A Flutter SQLite Todo App
publish_to: 'none'

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
